spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/rental
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      show_sql: true
  main:
    web-application-type: servlet
